version: '3.3'
services:
  decidim:
    container_name: decidim
    image: mautic/decidim
    build: .
    ports:
      - 3000:3000
    volumes:
      - bundle:/home/decidim/app/vendor
      - .:/home/decidim/app
    environment:
      DECIDIM_SYSTEM_EMAIL: "hello@myorg.com"
      DECIDIM_SYSTEM_PASSWORD: "my_insecure_password"
      DATABASE_URL: "postgres://decidim:my_insecure_password@pg:5432/decidim"
      REDIS_URL: "redis://default:my_insecure_password@redis:6379/1"
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_FORCE_SSL: "false"
      SMTP_ADDRESS: "mailer"
      SMTP_PORT: "25"
      SMTP_AUTHENTICATION: "none"
      PM2_RUN: decidim
      QUEUE_ADAPTER: sidekiq
      MEMCACHE_SERVERS: memcached:11211
    links:
      - pg
      - redis
      - mailer
      - memcached
    networks:
      - private
      - default

  sidekiq:
    container_name: decidim_async
    image: mautic/decidim
    volumes:
      - bundle:/home/decidim/app/vendor
      - .:/home/decidim/app
    environment:
      DECIDIM_SYSTEM_EMAIL: "hello@myorg.com"
      DECIDIM_SYSTEM_PASSWORD: "my_insecure_password"
      DATABASE_URL: "postgres://decidim:my_insecure_password@pg:5432/decidim"
      REDIS_URL: "redis://default:my_insecure_password@redis:6379/1"
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_FORCE_SSL: "false"
      SMTP_ADDRESS: "mailer"
      SMTP_PORT: "25"
      SMTP_AUTHENTICATION: "none"
      PM2_RUN: sidekiq
      QUEUE_ADAPTER: sidekiq
      MEMCACHE_SERVERS: memcached:11211
    depends_on:
      - pg
      - redis
      - mailer
      - memcached
    networks:
      - private

  pg:
    image: postgres:15-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "my_insecure_password"
      POSTGRES_USER: "decidim"
      POSTGRES_DB: "decidim"
    networks:
      - private

  redis:
    image: redis:7-alpine3.18
    command:
      - 'redis-server'
      - '--loglevel warning'
      - '--appendonly yes' # AOF mode
      - '--requirepass my_insecure_password' # min 64 chars in prod.
    volumes:
      - redis-data:/data
    networks:
      - private

  memcached:
    image: memcached:1.6.16-alpine
    networks:
      - private

  mailer:
    image: tophfr/mailcatcher
    ports:
      # SMTP port is 25, webinterface is on 80
      - 1080:80
    networks:
      - private
      - default

volumes:
  pg-data: {}
  redis-data: {}
  bundle: {}

networks:
  private: